package com.thizthizzydizzy.dizzyengine.world.object;
import com.thizthizzydizzy.dizzyengine.graphics.Material;
import com.thizthizzydizzy.dizzyengine.graphics.batch.Instanceable;
import com.thizthizzydizzy.dizzyengine.logging.Logger;
import java.util.Objects;
import org.joml.Vector3f;
public abstract class WorldObject{
    private boolean isDirty = true;
    private final Vector3f position = new Vector3f();
    private Material material;
    private boolean isStatic = false;

    public void render(){
        if(this instanceof Instanceable){
            throw new IllegalStateException("Instanceable WorldObjects cannot be rendered directly! Render these using Batches generated by a Batcher");
        }
    }

    public boolean isStatic(){
        return isStatic;
    }
    public void setStatic(boolean isStatic){
        if(isStatic!=this.isStatic)markDirty();
        this.isStatic = isStatic;
    }

    public void markDirty(){
        isDirty = true;
    }
    public void unmarkDirty(){
        isDirty = false;
    }
    public boolean isDirty(){
        return isDirty;
    }

    public Vector3f getPosition(){
        return position.get(new Vector3f());
    }
    public void setPosition(Vector3f position){
        if(!this.position.equals(position)&&isStatic){
            Logger.warn("A static object of type "+getClass().getName()+" just moved!");
            markDirty();
        }
        this.position.set(position);
    }

    public Material getMaterial(){
        return material;
    }
    public void setMaterial(Material material){
        if(!Objects.equals(material, this.material))markDirty();
        this.material = material;
    }
}
